# Generated by Django 3.2.12 on 2022-05-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp1', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_name', models.CharField(max_length=30)),
                ('Book_author', models.CharField(max_length=25)),
                ('Book_pages', models.IntegerField()),
                ('Book_price', models.FloatField()),
            ],
        ),
    ]
